### PR TITLE
chore: directly import dataclass

### LINKED ISSUE #39: Use Python's `from .. import ..` instead of just `import ..` for readability
Currently, the code looks like:

```python3
import dataclasses

@dataclasses.dataclass
class BuiltEntity:
    text: str
```

but we want it to look like:

```python3
from dataclasses import dataclass

@dataclass
class BuiltEntity:
    text: str
```

In certain places, using `from .. import ..` may be less readable, so just do what feels right!

### PR DESCRIPTION
**Pull request by imsamuel**
Closes #39.

Import `dataclass` directly instead of accessing it from `dataclasses`. Import statements are formatted using this user's suggestion from https://stackoverflow.com/a/20763446.

### CODE REVIEW

**Comment by neelkamath** [comment]
Sorry if the issue description wasn't very clear. You'll also need to update the other imports such as the `fastapi`, [`starlette`](https://github.com/neelkamath/spacy-server/blob/master/src/test_main.py#L12), etc. imports.

**Comment by imsamuel** [comment]
> Sorry if the issue description wasn't very clear. You'll also need to update the other imports such as the `fastapi`, [`starlette`](https://github.com/neelkamath/spacy-server/blob/master/src/test_main.py#L12), etc. imports.

Ah okay I see!

**Comment by imsamuel** [comment]
> Sorry if the issue description wasn't very clear. You'll also need to update the other imports such as the `fastapi`, [`starlette`](https://github.com/neelkamath/spacy-server/blob/master/src/test_main.py#L12), etc. imports.

Should `load` from `spacy` be directly imported? The `build_entity` function uses `spacy` for a parameter type.

**Comment by neelkamath** [comment]
Since functions like `load` may not make too much sense without the namespace, I personally wouldn't use `from .. import ..`, but you can use your own judgement in such cases.

**Review by neelkamath — CHANGES_REQUESTED** [review]
`main.py` looks good. Now we just need to update the imports in the [tests](https://github.com/neelkamath/spacy-server/blob/master/src/test_main.py) file.

**Comment by imsamuel** [comment]
> Since functions like `load` may not make too much sense without the namespace, I personally wouldn't use `from .. import ..`, but you can use your own judgement in such cases.

Okay!

**Comment by imsamuel** [comment]
> `main.py` looks good. Now we just need to update the imports in the [tests](https://github.com/neelkamath/spacy-server/blob/master/src/test_main.py) file.

Alright! 👌

**Review by neelkamath — APPROVED** [review]

**Pull request merged**
